_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  #WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_3shot_combine/model_reset_combine.pth"
  WEIGHTS: "F:/workspace/Daheng/Deep-learning-library/few-shot-object-detection-master/checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_base/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 3
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_3shot',)
  TEST: ('test_all',)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS: (200,)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 2000
  WARMUP_ITERS: 10
OUTPUT_DIR: "F:/workspace/Daheng/Deep-learning-library/few-shot-object-detection-master/checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_ft_all_3shot"